package com.example.herve.Study.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.herve.Study.bean.CurriculumBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CURRICULUM_BEAN".
*/
public class CurriculumBeanDao extends AbstractDao<CurriculumBean, Long> {

    public static final String TABLENAME = "CURRICULUM_BEAN";

    /**
     * Properties of entity CurriculumBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CurriculumId = new Property(1, int.class, "curriculumId", false, "CURRICULUM_ID");
        public final static Property ResId = new Property(2, int.class, "resId", false, "RES_ID");
        public final static Property CurriculumName = new Property(3, String.class, "curriculumName", false, "CURRICULUM_NAME");
        public final static Property Teacher = new Property(4, String.class, "teacher", false, "TEACHER");
    }


    public CurriculumBeanDao(DaoConfig config) {
        super(config);
    }
    
    public CurriculumBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CURRICULUM_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"CURRICULUM_ID\" INTEGER NOT NULL ," + // 1: curriculumId
                "\"RES_ID\" INTEGER NOT NULL ," + // 2: resId
                "\"CURRICULUM_NAME\" TEXT," + // 3: curriculumName
                "\"TEACHER\" TEXT);"); // 4: teacher
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CURRICULUM_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CurriculumBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCurriculumId());
        stmt.bindLong(3, entity.getResId());
 
        String curriculumName = entity.getCurriculumName();
        if (curriculumName != null) {
            stmt.bindString(4, curriculumName);
        }
 
        String teacher = entity.getTeacher();
        if (teacher != null) {
            stmt.bindString(5, teacher);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CurriculumBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCurriculumId());
        stmt.bindLong(3, entity.getResId());
 
        String curriculumName = entity.getCurriculumName();
        if (curriculumName != null) {
            stmt.bindString(4, curriculumName);
        }
 
        String teacher = entity.getTeacher();
        if (teacher != null) {
            stmt.bindString(5, teacher);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CurriculumBean readEntity(Cursor cursor, int offset) {
        CurriculumBean entity = new CurriculumBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // curriculumId
            cursor.getInt(offset + 2), // resId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // curriculumName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // teacher
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CurriculumBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCurriculumId(cursor.getInt(offset + 1));
        entity.setResId(cursor.getInt(offset + 2));
        entity.setCurriculumName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTeacher(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CurriculumBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CurriculumBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CurriculumBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
